kind: pipeline
name: build

workspace:
  base: /go

steps:
- name: test
  image: golang
  commands:
  - go test -v 
  - go build -o start
- name: start
  image: alpine
  detach: true
  commands:
  - start

