language: go
go:
  - 1.10.5
  - 1.11.2
#before_script:
#  - sudo apt-get install -qq sshpass
script:
  - go test -v
  - go build
#after_success:
#  - sshpass -p $SSH_PASS scp -o stricthostkeychecking=no golang-ci-example $SSH_USER@$SSH_HOST:~/
#  - sshpass -p $SSH_PASS ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST DB_HOST=$DB_HOST DB_USER=$DB_USER DB_PASS=$DB_PASS DB_BUCKET=$DB_BUCKET ./golang-ci-example
env:
  global:
notifications:
  on_success: never
  on_failure: never