name: Go

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Get versions
      id: get_version
      run: |
        echo ::set-output name=APP_VERSION::v0.0.0
      shell: bash

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -ldflags "-s -w" -o application_${{ steps.get_version.outputs.APP_VERSION }} ./main.go

    - name: Create release
      run: |
        gh release create "${{ steps.get_version.outputs.APP_VERSION }}" -t "${{ steps.get_version.outputs.APP_VERSION }}"
        gh release upload "${{ steps.get_version.outputs.APP_VERSION }}" application_* --clobber
