name: Go

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Get versions
      id: get_version
      run: |
        echo ::set-output name=APP_VERSION::${GITHUB_REF/refs\/tags\//}
      shell: bash

    - name: Build
      run: go build -ldflags "-s -w" -o start_${{ steps.get_version.outputs.APP_VERSION }} ./main.go

    - name: Test
      run: go test -v ./...

    - name: Prepare Release
      run: |
        mkdir output
        copy .\start .\output

    - name: Download amd64 artifact
      uses: actions/download-artifact@v2
      with:
        name: sftpgo_${{ steps.get_version.outputs.APP_VERSION }}

    - name: Create release
      run: |
        mv sftpgo_windows_x86_64.exe sftpgo_${SFTPGO_VERSION}_windows_x86_64.exe
        mv sftpgo_portable_x86_64.zip sftpgo_${SFTPGO_VERSION}_windows_portable_x86_64.zip
        gh release create "${APP_VERSION}" -t "${APP_VERSION}"
        gh release upload "${APP_VERSION}" start_* --clobber
