name: Go

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Get versions
      id: get_version
      run: |
        echo ::set-output name=APP_VERSION::${GITHUB_REF/refs\/tags\//}
      shell: bash

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -ldflags "-s -w" -o application_${{ steps.get_version.outputs.APP_VERSION }} ./main.go

    - name: Prepare Release
      run: |
        mkdir output
        copy .\application_${{ steps.get_version.outputs.APP_VERSION }} .\output

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: application_${{ steps.get_version.outputs.APP_VERSION }}

    - name: Create release
      run: |
        gh release create "${APP_VERSION}" -t "${APP_VERSION}"
        gh release upload "${APP_VERSION}" application_* --clobber
