name: Go

on:
  push:
    tags: 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Get versions
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -ldflags "-s -w -X dronetest/main.number=v.0.0.0 -X dronetest/version.commit=`git describe --always` -X dronetest/version.date=`date -u +%FT%TZ`" -o application_${{ steps.get_version.outputs.VERSION }} ./main.go

    - name: Create release
      run: |
        gh release create "${APP_VERSION}" -t "${APP_VERSION}"
        gh release upload "${APP_VERSION}" application_* --clobber
        gh release view "${APP_VERSION}"
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          APP_VERSION: ${{ steps.get_version.outputs.VERSION }}
